### ISSUE TITLE
Generate the event ID in the application

### ISSUE THREAD

**Issue by peschkaj** [peschkaj/eventsourcing#3]
In order to support k-ordered event IDs, we need to generate the event ID in the application.

- [x] Update `events` table to change `seq` to `event_id`. Change the type to `uuid` while we're there.
- [x] Update the in-memory and SQL `eventstore` modules to support the new name and type.
- [x] Generate the event ID in the application and ensure it's passed to the `eventstore` module during persistence.

**Comment by hallgren** [comment]
Hi Jeremiah, been watching the work you have been doing on your fork. It's really cool seeing others making changes to my work. 👍 

I also like the idea of using uuid as aggregate id. But as the uuid is not part of the standard library I have chosen to use a string (I have tried really hard to make the main module free from any dependency outside the standard library). That sad it's possible to override how the id is generated by the package function `eventsourcing.SetIDFunc` to convert a uuid to a string.

```go
	f := func() string {
		id, err := uuid.NewV7(uuid.MillisecondPrecision)
		if err != nil {
			panic(err)
		}
		return id.String()
	}
	eventsourcing.SetIDFunc(f)
```

When a new aggregate is created this function will be called to generate the aggregate id.

**Comment by peschkaj** [comment]
That's a good point about making the internal representation independent of the database. I've run into some issues in SQL Server, as an example, where UUIDs don't sort the same way in SQL Server as they do in the application (SQL Server's `UNIQUEIDENTIFIER` type is not RFC4122 compatible). Which, ultimately, means that one cannot store UUIDs in SQL Server without base62 encoding them or else shuffling the bytes on the way in and out.

I'll admit that my goal with these changes is to see if it's simple enough to use your library as a base for replicating a homegrown C# event sourcing library, but in Go. So far, everything has been straightforward.

**Comment by hallgren** [comment]
Will be interesting to follow.
